services:
  ipfs:
    image: ipfs/kubo:latest
    environment:
      IPFS_PROFILE: server
  tgbot:
    build:
      context: .
      dockerfile: tgbot/Dockerfile
    depends_on:
      ipfs:
        condition: service_healthy
    env_file:
      - .env.light
    restart: always
