services:
  ipfs:
    image: ipfs/kubo:latest
    environment:
      IPFS_PROFILE: server
  tgbot:
    build:
      context: .
      dockerfile: tgbot/Dockerfile
    depends_on:
      ipfs:
        condition: service_healthy
    env_file:
      - .env.light
    restart: always
    volumes:
      - /usr/lib/stc-tgbot-light:/usr/lib/stc-tgbot
      - /var/log/stc-tgbot-light:/var/log/stc-tgbot
