services:
  ipfs:
    image: ipfs/kubo:latest
    environment:
      IPFS_PROFILE: server
    ports:
      - 8080:8080
    volumes:
      - /Users/pasha/data-ipfs:/data/ipfs
  tgbot:
    build:
      context: .
      dockerfile: tgbot/Dockerfile
    depends_on:
      ipfs:
        condition: service_healthy
    env_file:
      - .env.light
    restart: always
    volumes:
      - /Users/pasha/tmp:/usr/lib/stc-tgbot
